ingress:
  - hostname: home.mingleedan.org
    service: https://localhost:8123  # Home Assistant 內部使用 HTTPS
    noTLSVerify: true              # <-- 新增這一行：告訴 cloudflared 忽略憑證驗證
  - service: http_status:404