name: Deploy Cloudflared Config

on:
  push:
    branches:
      - main
    paths:
      - 'cloudflared/config.yml'

jobs:
  deploy:
    name: Deploy to Local Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p ~/cloudflared
            cat <<'CONFIG' > ~/cloudflared/config.yml
${{ toJSON(fromJSON(file('cloudflared/config.yml'))) }}
CONFIG
            if [ "$(docker ps -q -f name=cloudflared-tunnel)" ]; then
                echo "Stopping and removing existing cloudflared container..."
                docker stop cloudflared-tunnel
                docker rm cloudflared-tunnel
            fi
            echo "Starting new cloudflared container..."
            docker run -d --name cloudflared-tunnel --restart unless-stopped \
              --network host \
              cloudflare/cloudflared:latest tunnel --no-autoupdate run --token ${{ secrets.CF_TUNNEL_TOKEN }}

